export const NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015'
export const RPC_URL = 'https://soroban-testnet.stellar.org'
export const HORIZON_URL = 'https://horizon-testnet.stellar.org'
export const FRIENDBOT_URL = 'https://friendbot.stellar.org'
export const EXPLORER_TX = 'https://stellar.expert/explorer/testnet/tx/'
export const EXPLORER_CONTRACT = 'https://stellar.expert/explorer/testnet/contract/'

export const CREDIT_LINE_CONTRACT = 'CDZ22YMZKGQZVHJKRJITRZREFKCTCURUKRC63G7ABIPO6SBHXTXL5Z4B'
export const BLEND_POOL = 'CCEBVDYM32YNYCVNRXQKDFFPISJJCV557CDZEIRBEE4NCV4KHPQ44HGF'
export const BLEND_ORACLE = 'CAZOKR2Y5E2OSWSIBRVZMJ47RUTQPIGVWSAQ2UISGAVC46XKPGDG5PKI'
export const XLM_SAC = 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC'
export const BLEND_USDC_SAC = 'CAQCFVLOBK5GIULPNZRGATJJMIZL5BSP7X5YJVMGCPTUEPFM4AVSRCJU'
export const BLEND_USDC_ISSUER = 'GATALTGTWIOT6BUDBCZM3Q4OQ4BO2COLOAZ7IYSKPLC2PMSOPPGF5V56'
export const CIRCLE_USDC_SAC = 'CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA'
export const CIRCLE_USDC_ISSUER = 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5'
export const READ_SOURCE_ACCOUNT = 'GDOZ44UXCLBBUTRQFOI6G5HQ5MGHG2LLEXALFKP4MTQBWEFHKPHDV52F'

export const ANCHOR_HOME_DOMAIN = 'tr-mock-anchor.fly.dev'
export const ANCHOR_BASE = 'https://tr-mock-anchor.fly.dev'
export const ANCHOR_TREASURY = 'GCLCZEQZ2THTEDAOFI66LACNPLY4OBKN7VKLEZFMBIHYKYQOW2W7T3Z6'
export const ANCHOR_USDC_ASSET = `stellar:USDC:${CIRCLE_USDC_ISSUER}`
export const ANCHOR_TRY_ASSET = 'iso4217:TRY'
export const ANCHOR_MAX_USDC = 300
export const ANCHOR_MAX_TRY = 3000

export const SCALAR_7 = 10_000_000n
export const SCALAR_12 = 1_000_000_000_000n
export const SAFETY_BUFFER = 0.97
export const SHOW_BACKGROUND = true
